name = "never-four"
main = "src/index.js"
compatibility_date = "2026-06-16"
workers_dev = true
preview_urls = true

[vars]
SITE_TITLE = "事不过三"
OWNER_NAME = "Pezy"

[secrets]
required = ["WRITE_TOKEN"]

[[d1_databases]]
binding = "DB"
database_name = "never-four"
database_id = "1da4d2b7-8f64-43aa-8746-0967c994271e"
migrations_dir = "migrations"
